# Generated by Django 5.2 on 2025-08-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='daily_intake_high',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='일일섭취량 상한', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='daily_intake_low',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='일일섭취량 하한', max_digits=20, null=True),
        ),
    ]
