# Generated by Django 5.2 on 2025-08-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_managements', '0002_alter_ingredient_daily_intake_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarysupplementsingredient',
            name='content',
            field=models.DecimalField(decimal_places=2, help_text='원료 함량', max_digits=20),
        ),
    ]
